### ISSUE TITLE
Add support for Cooked.wiki

### ISSUE THREAD

**Issue by Gymcap** [judemont/recipe_extractor#1]
Here are some examples:
https://www.tasteofhome.com/recipes/favorite-baked-spaghetti/
Becomes:
https://cooked.wiki/new/recent/47a923ae-5f5f-48df-81b7-e248385f5de8

https://www.averiecooks.com/easy-15-minute-spaghetti/
Becomes:
https://cooked.wiki/new/recent/8a383dc8-d019-415f-a74e-744a62193b90

https://www.favfamilyrecipes.com/nicks-authentic-italian-spaghetti/
Becomes:
https://cooked.wiki/new/recent/ee6b0448-e47b-4408-a8a3-2da97413ac95

And so on.

As you can see, all of these recipes from unsupported sites get translated into a consistent layout under cooked.wiki. by adding support for them, users could use any site that works with cooked.wiki to load recipes in the app. You could even automate the process of sending the users arbitrary recipe link to cooked.wiki to get the consistent format.

**Comment by judemont** [comment]
Very good idea, I'll try to integrate cooked.wiki soon !
